try{
}

catch(eror){
    console.log(eror);
}

finally{
    console.log("This always apear");
}
